services:
  web:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/app/public:ro
    links:
        - php
  php:
    image: fdc/php:dev
    hostname: php-dev
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./docker/root:/root
      - .:/var/www/app:rw
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    links:
        - db
    environment:
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
  db:
    image: mysql:8.4.2
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/default_schema.sql:/docker-entrypoint-initdb.d/00_base.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
