#!/usr/bin/env bash
#
# Safe bash settings
# -e            Exit on command fail
# -u            Treat unset variables as error
# -x            Print command before executing
# -o pipefail   Set error if piped command has error code
set -e -o pipefail

SCRIPT_DIR=$(dirname "$0")
cd "$SCRIPT_DIR/.."

echo "This is very destructive, executes 'rm -rf' on things like: .git, public"
echo "make sure you have looked over this script and are ok with what it will do"
echo
read -p "Shall we continue? " -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1 # handle exits from shell or function but don't exit interactive shell
fi

rm -rf ./public ./.git ./vendor ./docker/mysql/data/default_schema.sql

git init .
git add .
git commit -m 'initial commit'

# Can't install laravel into the current dir
docker-compose run -u root php composer create-project --prefer-dist laravel/laravel temp_laravel

for f in .env .env.example .gitattributes .gitignore; do
	if [ -f $f ]; then
		cat temp_laravel/$f >> $f
		rm -f temp_laravel/$f
	else
		mv temp_laravel/$f $f
	fi
done

mv temp_laravel/README.md README.laravel.md
mv temp_laravel/* .
rmdir temp_laravel

git add .
git commit -m 'initial laravel commit'

echo
echo "Review .env file, then:"
echo " dev/up"
echo " dev/artisan make:auth"
echo " dev/artisan migrate"
